/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as BillsRouteImport } from './routes/bills'
import { Route as IndexRouteImport } from './routes/index'
import { ServerRoute as DotwellKnownMicrosoftIdentityAssociationDotjsonServerRouteImport } from './routes/[.]well-known/microsoft-identity-association[.]json'

const rootServerRouteImport = createServerRootRoute()

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsRoute = BillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownMicrosoftIdentityAssociationDotjsonServerRoute =
  DotwellKnownMicrosoftIdentityAssociationDotjsonServerRouteImport.update({
    id: '/.well-known/microsoft-identity-association.json',
    path: '/.well-known/microsoft-identity-association.json',
    getParentRoute: () => rootServerRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bills': typeof BillsRoute
  '/unauthorized': typeof UnauthorizedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bills': typeof BillsRoute
  '/unauthorized': typeof UnauthorizedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bills': typeof BillsRoute
  '/unauthorized': typeof UnauthorizedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bills' | '/unauthorized'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bills' | '/unauthorized'
  id: '__root__' | '/' | '/bills' | '/unauthorized'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BillsRoute: typeof BillsRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
}
export interface FileServerRoutesByFullPath {
  '/.well-known/microsoft-identity-association.json': typeof DotwellKnownMicrosoftIdentityAssociationDotjsonServerRoute
}
export interface FileServerRoutesByTo {
  '/.well-known/microsoft-identity-association.json': typeof DotwellKnownMicrosoftIdentityAssociationDotjsonServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/.well-known/microsoft-identity-association.json': typeof DotwellKnownMicrosoftIdentityAssociationDotjsonServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/.well-known/microsoft-identity-association.json'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/.well-known/microsoft-identity-association.json'
  id: '__root__' | '/.well-known/microsoft-identity-association.json'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  DotwellKnownMicrosoftIdentityAssociationDotjsonServerRoute: typeof DotwellKnownMicrosoftIdentityAssociationDotjsonServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills': {
      id: '/bills'
      path: '/bills'
      fullPath: '/bills'
      preLoaderRoute: typeof BillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/.well-known/microsoft-identity-association.json': {
      id: '/.well-known/microsoft-identity-association.json'
      path: '/.well-known/microsoft-identity-association.json'
      fullPath: '/.well-known/microsoft-identity-association.json'
      preLoaderRoute: typeof DotwellKnownMicrosoftIdentityAssociationDotjsonServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BillsRoute: BillsRoute,
  UnauthorizedRoute: UnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  DotwellKnownMicrosoftIdentityAssociationDotjsonServerRoute:
    DotwellKnownMicrosoftIdentityAssociationDotjsonServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
