/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as SummariesRouteImport } from './routes/summaries'
import { Route as BillsRouteImport } from './routes/bills'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BankIndexRouteImport } from './routes/bank/index'
import { Route as BankSetupRouteImport } from './routes/bank/setup'
import { Route as BankSuccessItemIdRouteImport } from './routes/bank/success/$itemId'
import { ServerRoute as DotwellKnownMicrosoftIdentityAssociationDotjsonServerRouteImport } from './routes/[.]well-known/microsoft-identity-association[.]json'

const rootServerRouteImport = createServerRootRoute()

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const SummariesRoute = SummariesRouteImport.update({
  id: '/summaries',
  path: '/summaries',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsRoute = BillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BankIndexRoute = BankIndexRouteImport.update({
  id: '/bank/',
  path: '/bank/',
  getParentRoute: () => rootRouteImport,
} as any)
const BankSetupRoute = BankSetupRouteImport.update({
  id: '/bank/setup',
  path: '/bank/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const BankSuccessItemIdRoute = BankSuccessItemIdRouteImport.update({
  id: '/bank/success/$itemId',
  path: '/bank/success/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownMicrosoftIdentityAssociationDotjsonServerRoute =
  DotwellKnownMicrosoftIdentityAssociationDotjsonServerRouteImport.update({
    id: '/.well-known/microsoft-identity-association.json',
    path: '/.well-known/microsoft-identity-association.json',
    getParentRoute: () => rootServerRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bills': typeof BillsRoute
  '/summaries': typeof SummariesRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/bank/setup': typeof BankSetupRoute
  '/bank': typeof BankIndexRoute
  '/bank/success/$itemId': typeof BankSuccessItemIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bills': typeof BillsRoute
  '/summaries': typeof SummariesRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/bank/setup': typeof BankSetupRoute
  '/bank': typeof BankIndexRoute
  '/bank/success/$itemId': typeof BankSuccessItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bills': typeof BillsRoute
  '/summaries': typeof SummariesRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/bank/setup': typeof BankSetupRoute
  '/bank/': typeof BankIndexRoute
  '/bank/success/$itemId': typeof BankSuccessItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bills'
    | '/summaries'
    | '/unauthorized'
    | '/bank/setup'
    | '/bank'
    | '/bank/success/$itemId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bills'
    | '/summaries'
    | '/unauthorized'
    | '/bank/setup'
    | '/bank'
    | '/bank/success/$itemId'
  id:
    | '__root__'
    | '/'
    | '/bills'
    | '/summaries'
    | '/unauthorized'
    | '/bank/setup'
    | '/bank/'
    | '/bank/success/$itemId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BillsRoute: typeof BillsRoute
  SummariesRoute: typeof SummariesRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  BankSetupRoute: typeof BankSetupRoute
  BankIndexRoute: typeof BankIndexRoute
  BankSuccessItemIdRoute: typeof BankSuccessItemIdRoute
}
export interface FileServerRoutesByFullPath {
  '/.well-known/microsoft-identity-association.json': typeof DotwellKnownMicrosoftIdentityAssociationDotjsonServerRoute
}
export interface FileServerRoutesByTo {
  '/.well-known/microsoft-identity-association.json': typeof DotwellKnownMicrosoftIdentityAssociationDotjsonServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/.well-known/microsoft-identity-association.json': typeof DotwellKnownMicrosoftIdentityAssociationDotjsonServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/.well-known/microsoft-identity-association.json'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/.well-known/microsoft-identity-association.json'
  id: '__root__' | '/.well-known/microsoft-identity-association.json'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  DotwellKnownMicrosoftIdentityAssociationDotjsonServerRoute: typeof DotwellKnownMicrosoftIdentityAssociationDotjsonServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summaries': {
      id: '/summaries'
      path: '/summaries'
      fullPath: '/summaries'
      preLoaderRoute: typeof SummariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills': {
      id: '/bills'
      path: '/bills'
      fullPath: '/bills'
      preLoaderRoute: typeof BillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank/': {
      id: '/bank/'
      path: '/bank'
      fullPath: '/bank'
      preLoaderRoute: typeof BankIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank/setup': {
      id: '/bank/setup'
      path: '/bank/setup'
      fullPath: '/bank/setup'
      preLoaderRoute: typeof BankSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank/success/$itemId': {
      id: '/bank/success/$itemId'
      path: '/bank/success/$itemId'
      fullPath: '/bank/success/$itemId'
      preLoaderRoute: typeof BankSuccessItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/.well-known/microsoft-identity-association.json': {
      id: '/.well-known/microsoft-identity-association.json'
      path: '/.well-known/microsoft-identity-association.json'
      fullPath: '/.well-known/microsoft-identity-association.json'
      preLoaderRoute: typeof DotwellKnownMicrosoftIdentityAssociationDotjsonServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BillsRoute: BillsRoute,
  SummariesRoute: SummariesRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  BankSetupRoute: BankSetupRoute,
  BankIndexRoute: BankIndexRoute,
  BankSuccessItemIdRoute: BankSuccessItemIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  DotwellKnownMicrosoftIdentityAssociationDotjsonServerRoute:
    DotwellKnownMicrosoftIdentityAssociationDotjsonServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
